### ISSUE TITLE
Loading Dll files, complete steps

### ISSUE THREAD

**Issue by wsuphappyhour** [krishKM/Modern-UI-Components-for-VBA#12]
Hi could you please describe how to do "Dll part".
I get Object or variable not set on:
  Files = gDll.DLL.ShowDialogForFileArray("Feel free to drop many files", True, F)
Thanks

**Comment by wsuphappyhour** [comment]
Appearantly vba is not recognizing path function
so changing it to native VBA solves the problem and Dll is loaded

Where to change:
Public Function GetBasePath()
'---------------------------------------------------------------------------------------
' Procedure : GetBasePath
' Author    : KRISH
' Date      : 21/05/2018
' Purpose   : Returns app working path
' Returns   :
'---------------------------------------------------------------------------------------
'

    Dim FN As String
    FN = ThisWorkbook.Path
    If VBA.Right(ThisWorkbook.Path, 1) <> "\" Then FN = FN & "\"
    GetBasePath = FN
End Function

**Comment by krishKM** [comment]
Thank you for this. Also please note, Excel sheet hasn't been updated for a while. The function names might be different. Please double check the function names before copying.
