### ISSUE TITLE
SaveClipboardToImage() giving error messages

### ISSUE THREAD

**Issue by annaemde** [krishKM/Modern-UI-Components-for-VBA#14]
Hi Krish,
thank you very much for the new version - saving clipboard to another path works fine now!
But I still get error messages:
1) "Assembly... ZintNetLib error..."
2) "Assembly... Newtonsoft.Json..."  

Error message 2) occurs when I give a path in SaveClipboardToImage().
Kind regards
Anna

**Comment by krishKM** [comment]
Regarding error 2. Newtonsoft.Json is required in many other basic functions. I will see if I can separate this dll in later versions. 

Regarding error 1: Are you sure you are not using any of barcode commands? I have just tried deleting ZintNetLib.dll and it works fine without an error. Can you tell me what system you are using? Excel/Access? 32bit, 64bit? office version?

Thanks 
Krish

**Comment by krishKM** [comment]
Hi Anna,

you don't need to download any dlls. All required dlls are supplied in that bin folder. Have the bin folder wherever your application is and it will work.
regards
Krish
