### ISSUE TITLE
Feature Request: change body color of Dialog Box and progress-bar

### ISSUE THREAD

**Issue by linety** [krishKM/Modern-UI-Components-for-VBA#15]
first of all, I have to say that I'm very grateful for all your work.

 I have a small request to make is the ability to change the body color (and possibly also the border color /style ) of dialogbox and the progress bar. for now I can only change the color of the title and the color of the ribbon in the dialogbox , and since in my app I have mainly white background the dialogbox looks weird since it has transparent borders and is white too .

I hope that this is not too much to ask.
best regards

**Comment by krishKM** [comment]
Hey thanks for your ideas. I've made some changes for dialogbox and progressbar. Download the new sample and check it out. Thanks again.

**Comment by lajjutz** [comment]
Hello, I've already tested the new sample, and it works, thanks for the improvement.

**Comment by linety** [comment]
ty very much, god bless you.
