### ISSUE TITLE
ShowContextMenuA Bug

### ISSUE THREAD

**Issue by linety** [krishKM/Modern-UI-Components-for-VBA#16]
ShowContextMenuA is, for the most part, working as intended the only issue I noticed is that, when the menu first appears it has the first item selected by default, so If open the menu and exit without selecting an item, the menu will have still have the first item selected and executes the actions related to that item, of course, this can be fixed by adding an item at the top and not setting any action upon its selection but this makes the menu weird and for sure not as it was intended to work .

on the other had the ShowContextMenu doesn't have this bug, but the first item of the menu always appears to be selected when hovering over other items in the menu (ps : even in the gif https://github.com/krishKM/VBA_TOOLS/raw/master/screenshots/CoolContextMenu.gif , the first item appears always as selected, yet in that gif the first item looks blue, while other items when hovered over are green, but in the accdb sample, all items are green even the first item)

Ty for your all the work put into this.
Best Regards

**Comment by krishKM** [comment]
Hey thanks again for the bug. I've corrected this please check the latest update and let me know.

Btw. "so If open the menu and exit without selecting an item, the menu will have still have the first item selected" => if you press Esc no item will be selected. This is true for both ContextMenus.

**Comment by linety** [comment]
ty for the fix. great work man!
