### ISSUE TITLE
I want to use the progress bar and open file features . . .

### ISSUE THREAD

**Issue by BugleBoyMusic** [krishKM/Modern-UI-Components-for-VBA#18]
but even the sample accdb does not work without a Newsoft.json file.  Can you help?
Jim Faull

**Comment by BugleBoyMusic** [comment]
Forgot to include my email:
jim@jimfaull.com
Thanks!

**Comment by krishKM** [comment]
Just download and have the bin folder in your project root location. The bin folder has all the necessary dlls. Have you tried this?

**Comment by BugleBoyMusic** [comment]
Thanks for your quick response!!

 

I unzipped the Json110r2.zip and copied that Bin folder.  Is that the right one?

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by krishKM** [comment]
The bin folder can be found here.
https://github.com/krishKM/Modern-UI-Components-for-VBA/tree/master/samples/

Download and have the bin folder where you've placed the vba_tools.dll. vba_tools will look into the bin folder and find necessary dlls.  Let me know if this has helped.

**Comment by BugleBoyMusic** [comment]
I try to browse and still get an exception error that it cannot see the Newsoft.Json file.  I also want to capture the path of a file by putting it in an unbound text box.  I guess it will do this.

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by BugleBoyMusic** [comment]
Here tis

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by BugleBoyMusic** [comment]
I will be glad to do a quick GoToMeeting so you can see.

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by krishKM** [comment]
Unfortunately I have to go now. Like I said, download the bin folder where you downloaded the sample accdb file from and place where your access file is. I might be able to help tomorrow morning or afternoon. Have a nice day.

**Comment by BugleBoyMusic** [comment]
Thanks for you help so far.  I love the work you have done!  Excellent!

 

We are out tomorrow to have Thanksgiving with my wife’s 93 year old mother.  I could do anytime Saturday or Monday of next week.  Did I notice you are in London?

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by BugleBoyMusic** [comment]
Krish,

 

The good news is that the program runs fine on my Windows 10 computer, but the bad news is it does not work on my Windows 7 computer.  Both are running Access 365.  Obviously, something is missing on my Windows 7 computer.  Any ideas?  I will need to be sure that all my users can use this wonderful feature.

 

You can see the pic I have attached.

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by krishKM** [comment]
Good Morning, i will check this for you. I believe this might be because of some .NET framework dlls are missing in your Windows 7 machine. Windows 7 is not supported anymore by Microsoft and .NET 4.6 is the current default. However i will check this for you.

**Comment by BugleBoyMusic** [comment]
Thanks for getting back! The Windows 7 machine has .NET 1.1 and 4.7.2.  Should I uninstall and re-install these?

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by krishKM** [comment]
No, they are both fine. What error message are you getting on Win7?

**Comment by BugleBoyMusic** [comment]
Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>

**Comment by krishKM** [comment]
I guess you are replying GitHub notification Emails and I cannot see any pictures. Could you please use the web GitHub comment section to upload any pictures.

**Comment by BugleBoyMusic** [comment]
Sorry!
![themodulator20yearswhiteoutline375](https://user-images.githubusercontent.com/45266794/49021461-ae67e900-f160-11e8-9e66-335b10baf6b8.png)

![frmfiledrag](https://user-images.githubusercontent.com/45266794/49021432-98f2bf00-f160-11e8-87e8-29a40a5c0bb4.jpg)
Thanks!
Jim

**Comment by BugleBoyMusic** [comment]
![binscreen](https://user-images.githubusercontent.com/45266794/49021532-d5261f80-f160-11e8-9515-c524f6b1791b.jpg)
I meant to send this one.

**Comment by BugleBoyMusic** [comment]
I would be glad to remote you in to take a look.

**Comment by krishKM** [comment]
have released an update removing the JSon bindings. please try to download the vba_tools.dll and the bin folder. please let me know if this has worked

**Comment by BugleBoyMusic** [comment]
Is there any difference in the 64 bit version?  I tried both.

**Comment by krishKM** [comment]
x64 is for 64bit office. Do you have 64bit office?

**Comment by BugleBoyMusic** [comment]
No

**Comment by krishKM** [comment]
are you able to offer remote invitation to your PC? what remote tool are you using?

**Comment by BugleBoyMusic** [comment]
The best on is:
https://www.fastsupport.com/420296302

**Comment by BugleBoyMusic** [comment]
one

**Comment by BugleBoyMusic** [comment]
https://www.fastsupport.com/165671428
Try this one.  or go to www.bugleboymusic.com, roll over Support menu and do the GoToMeetingLogin
meeting# 293-994-221

**Comment by BugleBoyMusic** [comment]
That took forever!
go to www.bugleboymusic.com, roll over Support menu and do the GoToMeetingLogin
meeting# 293-994-221

**Comment by BugleBoyMusic** [comment]
The Windows 10 computer that works was using Windows Defender for the firewall.  I changed the Windows 7 firewall to Windows Defender and get the same result you were getting.

Thanks for you work on this.  I am looking forward to using your products.

**Comment by BugleBoyMusic** [comment]
Thanks. I will jump on it after breakfast.

Blessings!

Jim

www.BugleBoyMusic.com

**Comment by krishKM** [comment]
Hi Jim, i installed .NET 4.7.2 and did not have any issue like you. After some research i found, sometimes DLLs from online are being blocked from loading dynamically.

[see this post](https://stackoverflow.com/a/21770848/1684486)

Please right click on the Newtonsoft.Json.dll and click properties and click "unbock" to allow this dll to be loaded.  please let me know how this went. I also made some config changes to the vba_tools.dll. Please also get the new dll from the sample folder. thank you for your cooperation.

**Comment by BugleBoyMusic** [comment]
I unblocked all of the DLLs.  Still get the error.  Does it matter that the Opens With shows an unknown program?

**Comment by krishKM** [comment]
Any chance that I could remote into your PC and have a look? I'm very curious about this issue.

**Comment by BugleBoyMusic** [comment]
Jim's Instant Meeting 293-994-221 

Please join my meeting from your computer, tablet or smartphone. 
https://www.gotomeet.me/JimFaull 

You can also dial in using your phone. 
United States: +1 (312) 757-3121 

Access Code: 293-994-221 

First GoToMeeting? Let's do a quick system check: 
https://link.gotomeeting.com/system-check

**Comment by krishKM** [comment]
It's working after unblocking all Dlls including vba_tools.dll

**Comment by BugleBoyMusic** [comment]
Krish,

 

Hope you had a wonderful Christmas season!

 

I have one issue.  When checking for dependencies for VBA_Tools.dll, the file CCMSWrapper is reported as missing.  Any wisdom on this?

 

Blessings!

 

Jim Faull

 

(770)919-2520 Office

(770)653-5094 Cell

Bugle Boy Music | 1310 Parkview LN NW | Kennesaw, GA 30152

 

 <http://bugleboymusic.com/>
