### ISSUE TITLE
Feature Request :menu width for  ShowContexMenu

### ISSUE THREAD

**Issue by linety** [krishKM/Modern-UI-Components-for-VBA#21]
hey brother ,

first, ty for the continued support for this great project,
as the title says; so far we can only define the icon bar width but not the menu width and thus the menu span until the edge of the form.  and thus the only way to keep using this is to put the button that calls the menu to be close to the edge of the form.

I hope that this is feasible, ty in advance.
also, any tweaking that can be done to improve the performances of the menu; since for using this a lot , I noticed that one i open the app, the first time i will click the menu button (nothing will happen ) its after that the menu will work just fine. ( any idea about how to fix this ? )

tnx in advance

**Comment by krishKM** [comment]
Thanks for using this dll. Can you show me some screenshots regarding issue1?

issue 2. You mean the very first call?

**Comment by linety** [comment]
issue 2. You mean the very first call? yes

**Comment by linety** [comment]
and for the 1st issue i was wrong about the menu spanning to the end of the window ( i moved the button to the middle to see this ) but still the menu is too wide ( i wan to make "actions" button instead of the "cancel sale" and put a menu there ( the current menu is too wide ) https://prnt.sc/lp1drv

**Comment by krishKM** [comment]
Thanks for this, i will look into this.

**Comment by krishKM** [comment]
Please get the latest update. 
When you call the context menu, you can now pass the window handler (HWND) to the function.
i.e. `gDll.ShowContexMenu(MenuITems, Me.hwnd)`
Doing this, will allow the DLL to determine if your form is closer to the "edge" of the underlying monitor. If so, the menu is then placed inwards. Hope this helps.

**Comment by linety** [comment]
ty for this explanation, adding the hwnd argument makes the menu spawn on the left side , but the question still remains, can't there be a way to set the menu width ?

best regards,

**Comment by linety** [comment]
hey again,

i want to explain my self further on this request, from the screenshot that i sent , i want to replace the cancel button with a button that has a drop down menu ; like the style of the combobox ( but you know .. the combobox is not good looking plus it has it's huge deal of issues and limitations , so could it be possible to have a different seperate fuction that would make a classic drop down menu https://prnt.sc/lq1e7z spaning always under the button and not in the click position .

such an option would give more flexibility to work with .

as always , thanks for the huge support and the great effort , may god bless you.

**Comment by krishKM** [comment]
Made some changes. you can now use MenuWidth to control the width or pass -1 for auto sized column.
Thanks for the feedbacks.

**Comment by linety** [comment]
I tried the new project version and the MenuWidth argument doesn't seem to affect the menu width at all.

can you please check it

**Comment by krishKM** [comment]
Sorry for the late response.

1: menuWidth bug corrected.
2: menu not closing also corrected.

3: x,y locaiton. i will look into this. Currently mouse pointer is used

**Comment by linety** [comment]
ty for your work.

**Comment by krishKM** [comment]
Please close this ticket if this has been sorted
