### ISSUE TITLE
ProgressBar doesn't allow new title to be assigned

### ISSUE THREAD

**Issue by AnderBot5** [krishKM/Modern-UI-Components-for-VBA#22]
I've just started using your progress bar functionality, which is awesome. The one thing that doesn't seem to work is setting the title of the dialog box/progress bar. Even in the example you provide, the string you pass to it doesn't get displayed. The other text does, but the title does not. 

Also, is there any way to change the color of the progress bar itself?

**Comment by krishKM** [comment]
Hi there, thanks for pointing this bug. This has been corrected and a new version published. Please try the updated version and let us know. 

Kind regards

**Comment by AnderBot5** [comment]
I just tried the updated version, and now the progress bar doesn't work at all. It keeps coming back with an error 91 (object variable or with block variable not set). Note that I just upgrade computers, so it may be something in my settings. But even when using the Sample DB you updated, that doesn't appear to work either.

**Comment by AnderBot5** [comment]
That worked perfectly, I forgot I had to do that step before hand as well. Thanks!

**Comment by krishKM** [comment]
did the progressbar show correct title and were you able to change progressbar colour?

**Comment by AnderBot5** [comment]
It showed the correct title, but haven't tried changing the progressbar color. Is that just another parameter I need to pass to it? Similar to the background color and header color?

**Comment by krishKM** [comment]
yes you can pass any colour you wish to `pBarColour` parameter. or by default bootstrap.success colour is used.
