### ISSUE TITLE
Question : did you use any tool when exporting unmanaged dlls 

### ISSUE THREAD

**Issue by linety** [krishKM/Modern-UI-Components-for-VBA#25]
i found these tools like [UnmanagedExports](https://www.nuget.org/packages/UnmanagedExports)  or [dllexports](https://github.com/3F/DllExport/) , did you use any one of these tools or when creating the vba_tools.dll or similar tools, im trying to make use of other languages for performant code execution, unit testing,portable code across projects which is very difficult to make with vba to say the least. 

any help would be appreciated, thanks in advance.

**Comment by krishKM** [comment]
HI Linety, yes i'm using unmanagedExports. hope this helps
