### ISSUE TITLE
"Object required" error - ImageControlGetImage

### ISSUE THREAD

**Issue by FLJerseyboy** [krishKM/Modern-UI-Components-for-VBA#27]
Hello Krish - very excited that I might be able to use this. However, am getting a runtime error 424, "Object required." The VBATools.dll and the bin folder are both in my app's own folder, and I've unblocked VBATools.dll. Have tried it both from a form's OnCurrent event and from a button's OnClick -- no difference.

(My app is running from OneDrive, in case that makes a difference.)

BTW -- you've put a lot of work into this useful toolkit. Well done!

**Comment by FLJerseyboy** [comment]
P.S. Using Access 2016, 64-bit Windows 10.

**Comment by krishKM** [comment]
I have just tested on an VM installing win10 + x64 acces and it worked for me.
anyway have fixed some other bugs and uploaded the new dll. check out the sample folder for downloads and let me know.
