### ISSUE TITLE
Please update dll_text.xlsm 

### ISSUE THREAD

**Issue by jerryngm** [krishKM/Modern-UI-Components-for-VBA#31]
Hi,

Could you please update for code for Excel version as it's not working 

I'm keep getting this error message.
![image](https://user-images.githubusercontent.com/21076025/59316397-9f621600-8d01-11e9-94e3-937e9628a5e1.png)

Thank you!

**Comment by krishKM** [comment]
Sorry we haven't updated the Excel file for long time. Can you tell us which function you were trying to use?
Please download the latest Excel file. we've corrected few things
