### ISSUE TITLE
Hyperlink in Toast messages not working

### ISSUE THREAD

**Issue by TheDemonized** [krishKM/Modern-UI-Components-for-VBA#34]
I tried with Access 2010 and 2016
Local function calls and DoCmd functions are not working (anymore?).. 
Also in the sample file the function does not work for me

**Comment by bobsan42** [comment]
Yes, I noticed the same thing, although I have no older version of the dll.
The hyperlinks and callback functions in Toast do not work.
Also the intended formatting with <b> tag does not work for me.

**Comment by krishKM** [comment]
Hyperlinks bug corrected -.-

@bobsan42 : what do you mean by "tag does not work for me." can you open a new issue and explain more please?

**Comment by bobsan42** [comment]
What I meant was the BOLD HTML tag, but of course the system took it as formatting tag.
I saw a bold-tag in your examples so I assumed you intended to have bold text in your toast messages. It just doesn't work for me. I don't necessarily see it as a bug, 
`<b>`
