### ISSUE TITLE
FEATURE Request: FileDialogue Drag and Drop Support for Outlook

### ISSUE THREAD

**Issue by Saphirah** [krishKM/Modern-UI-Components-for-VBA#40]
hey Krish, thank you for your awesome tools, i used them quite a lot in my current access project.
Right now the drag and drop box does not allow to directly get files from outlook. It only works with the windows explorer.
It would be awesome if the box would support files dragged in by outlook, as this allows a faster workflow and increases productivity, whereas right now the user needs to save the file first, before dragging it in.
If there are any problems referencing these files, you could maybe first save the file on a specific path and then return a link to that file.

Cheers mate, and thank you for your time.

**Comment by krishKM** [comment]
Hi Saphira, thank you and this has been fixed for 64bit office
