### ISSUE TITLE
Color Button of Dialog Box is not changing

### ISSUE THREAD

**Issue by lajjutz** [krishKM/Modern-UI-Components-for-VBA#43]
Hello Krish

I was working with another database using your last update of the dlls files, and I realize that the color of the button of the dialog box are not changing despite changing the colors:

gDll.ShowDialog(Me.Text2.value, vbInformation, "Title", "OK", "", "#A25151", "#FFFFFF")
gDll.ShowDialog(Me.Text2.value, vbInformation, "Title", "OK", "", "#00C851", "#FFFFFF")

![image](https://user-images.githubusercontent.com/44538069/96040617-d7aec280-0e27-11eb-8076-400063538957.png)

Previous version, when changing the "ThemeBg" color, changed also the button color using the same color.

Maybe you can check out what's going on with this..

Thanks in advance.

**Comment by krishKM** [comment]
Fixed. Update released
