### ISSUE TITLE
Love the idea, but can't compile due to Public gBootstrap   As New Tbootstrap

### ISSUE THREAD

**Issue by pchambless** [krishKM/Modern-UI-Components-for-VBA#48]
I am anxious to put this package into action!  This may not even be a big deal because, in the short run, I'm really interested in converting my Access table to JSON.  When I try to compile I get error on **Public gBootstrap   As New Tbootstrap**.  Now, what I did was copy all the modules and class modules in the **dll_test.accdb** which maybe I did not need to do.  I've used Access for almost 30 years, so I've been around the block, but I would not call myself a 'developer' - more like a 'prototyper'.  Thanks if you can point me in a direction.  If you can tell me what I need to do to create a **Tbootstrap** type, That may work...

**Comment by krishKM** [comment]
hi, are you sure you've copied all the class modules? there is a class module called TBootstrap. if you have this in your application then it should work.

**Comment by pchambless** [comment]
Ohhhh!  My bad!  Thank you for you quick reply!

------ Original Message ------

**Comment by pchambless** [comment]
I hadn't copied in the TDialog either.  That would probably be an issue as well, ha ha.   I will close this issue.
