### ISSUE TITLE
Feature Request: Open File Drag & Drop stays open until closed

### ISSUE THREAD

**Issue by alikona05** [krishKM/Modern-UI-Components-for-VBA#50]
Hi kishKM,

Thank you for the samples here, they really are wonderful.

I was able to adapt your Open File Drag & Drop component into my database. In my database, once a file is dropped, it is copied into a designed directory based on my record ID. 

Most of my files are being added through outlook, so its generally just 1 file dragged at a time. The issue is that my users have to keep clicking the button to open the drag & drop field after each file (sometimes there are multiple to attach to the same record). 

I was wondering if it was possible to a) embed the drag & drop field into a form or b) to modify the component in a way that the drag & drop window stays open until you hit the x button, so you could drag and drop single files multiple times.

**Comment by krishKM** [comment]
Drop stays open until closed : Done.
