### ISSUE TITLE
Drag-n-drop from Outlook do not work with the 64bit office

### ISSUE THREAD

**Issue by gontranharvey** [krishKM/Modern-UI-Components-for-VBA#51]
I was able to make the sample database work on 64 bits but the drag-n-drop only work for files from Windows explorer but not from Outlook attachment. The 32-bit version works fine.
When you drop the file it fires nothing.

**Comment by krishKM** [comment]
Office 64bit + Outlook attachment bug is now fixed.

**Comment by gontranharvey** [comment]
Thanks a lot
