### ISSUE TITLE
Solidworks vba + modern ui not working

### ISSUE THREAD

**Issue by IamTheVector** [krishKM/Modern-UI-Components-for-VBA#52]
I cant make it work with solidworks. Could you help? All the code appears in red. 

![image](https://user-images.githubusercontent.com/11708789/151327803-58e658fa-b51b-4726-84a2-898f04b29088.png)

**Comment by krishKM** [comment]
I'm sorry I have never worked with Solidworks. Having said that you can remove the red lines they are not needed. I'm afraid even then you need further modification as the current project is mainly targetting Ms Access environment. - Good luck.

**Comment by IamTheVector** [comment]
I will make a test tomorrow, there are many other red lines, I was just guessing if I need to add some references or external objects or else. If you can support me I'm sure I can make it work.
