### ISSUE TITLE
Show Context Menu

### ISSUE THREAD

**Issue by US-Ali** [krishKM/Modern-UI-Components-for-VBA#6]
I felt this deserves it's own thread especially for those who might want to contribute to it in future. It's a perfect solution and as usual you have done a very good job. Thank you for helping other developers.

I was able to set the "**iconBarWidth**" of **ShowContextMenuA** to 0 just to see how it works and it was good. I tried to adjust the size of the "**rowHeight**" from 44 to something like 15 or 20 but it doesn't seem to be working. I tried expanding that too for **ShowContexMenu** without any luck. I know this is still under development hence the reason why.

**Comment by krishKM** [comment]
Hi and thank you for your valuable time. RowHeight is fixed now. WIll look into menuWidth later on.
Thanks again
